### ISSUE TITLE
请问下，4090显卡应该如何修改设置，不让它跑共享显存

### ISSUE THREAD

**Issue by wangjingyuancuc** [TMElyralab/MusePose#10]
在win11下用wsl装的ubuntu，4090显卡应该如何修改设置，不让它跑共享显存
<img width="469" alt="微信图片_20240529221512" src="https://github.com/TMElyralab/MusePose/assets/154451879/56ca31d0-21e0-420d-996a-110c4cb57173">

**Comment by BlacknoSheep** [comment]
调小尺寸参数
参考 https://github.com/TMElyralab/MusePose/issues/6#issuecomment-2136933975
我16G显存最大 512x512
24G显存 估计可以 640*640
```
python test_stage_2.py --config ./configs/test_stage_2.yaml -W 640-H 640
```

**Comment by hben35096** [comment]
python test_stage_2.py --config ./configs/test_stage_2.yaml -W 640 -H 640

**Comment by FangSen9000** [comment]
@wangjingyuancuc Hello, I noticed that you have been researching MusePose training recently. Can you share your musePose training script? I have been having problems with my training.
