### ISSUE TITLE
Video test file Do you know what I did wrong

### ISSUE THREAD

**Issue by CoolCuda** [TMElyralab/MusePose#12]
hello

do you know why I have this result ?
watch the video result : 
https://github.com/TMElyralab/MusePose/assets/150287877/76fff4bd-9759-46d8-8f7b-686a4732724f
![123](https://github.com/TMElyralab/MusePose/assets/150287877/1a6ff4d3-d326-4808-9dd6-d13ab44fdfed)

thank you

**Comment by czk32611** [comment]
> hello
> 
> do you know why I have this result ? watch the video result : https://github.com/TMElyralab/MusePose/assets/150287877/76fff4bd-9759-46d8-8f7b-686a4732724f ![123](https://private-user-images.githubusercontent.com/150287877/334966670-1a6ff4d3-d326-4808-9dd6-d13ab44fdfed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzI4NjQsIm5iZiI6MTcxNzAzMjU2NCwicGF0aCI6Ii8xNTAyODc4NzcvMzM0OTY2NjcwLTFhNmZmNGQzLWQzMjYtNDgwOC05ZGQ2LWQxM2FiNDRmZGZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzhhNDA5MDYzNDdhMGE3OTEzMWJhMjM5MWM1ZmIyNjdiYTIxZmQ4NjhiYWIzMjczN2U4MTUxNDJkNGNjZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qcu41vVeVLidKz0Cdy0hf-5_rPEYtRW-xmH2MYzaRMM)
> 
> thank you

The input video to `test_stage_2.py` should be a video of pose sequences. Currently, it seems that you input a video of rgb pixels.

**Comment by CoolCuda** [comment]
Thank you czk32611 :)
Do you know where I can find any pose sequence video ?

**Comment by czk32611** [comment]
> Thank you czk32611 :) Do you know where I can find any pose sequence video ?

You can run pose alignment according to [here](https://github.com/TMElyralab/MusePose?tab=readme-ov-file#pose-alignment)

**Comment by CoolCuda** [comment]
Thank you my friend I will try this
