### ISSUE TITLE
关于align_demo奇怪的结果，感觉像大猩猩？

### ISSUE THREAD

**Issue by zhanghongyong123456** [TMElyralab/MusePose#15]
这是我的align效果，这样的该如何处理呢
![image](https://github.com/TMElyralab/MusePose/assets/48466610/ec51afea-f09e-496b-952f-5961f6c2e32c)

这是最终驱动结果：
![image](https://github.com/TMElyralab/MusePose/assets/48466610/98f442d4-e137-4395-9419-a61dbee548cf)

**Comment by czk32611** [comment]
应该是输入图片的右手被挡住了或者角度问题，识别得特别短，所以align就不准了

align是一个非常复杂的问题，我们非常欢迎大家contribute～

**Comment by zhanghongyong123456** [comment]
> 应该是输入图片的右手被挡住了或者角度问题，识别得特别短，所以align就不准了
> 
> align是一个非常复杂的问题，我们非常期待大家contribute～

请问：和图像分辨率以及视频分辨率有关系吗，有什么技巧吗，这是我另一个测试案例，左手手臂为什么会那么长：

https://github.com/TMElyralab/MusePose/assets/48466610/32708f20-12f9-479e-ba89-1aaccd362384

这是原始图片和  视频：
![004](https://github.com/TMElyralab/MusePose/assets/48466610/ad4b3893-5d45-44e8-9f57-cf4dd0adb031)

https://github.com/TMElyralab/MusePose/assets/48466610/ee7c7f44-f806-4c3d-9180-b06b42c20b00

**Comment by zhanghongyong123456** [comment]
> 应该是输入图片的右手被挡住了或者角度问题，识别得特别短，所以align就不准了
> 
> align是一个非常复杂的问题，我们非常期待大家contribute～

相同的 参考图和驱动视频，我测试了 champ 预处理 方式，得到的效果很完美，
https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md

https://github.com/TMElyralab/MusePose/assets/48466610/b0ff004d-7dfb-4544-947b-fe63366d057a，这里需要处理dwpose应该去掉人脸关键点检测
