### ISSUE TITLE
yolox link points to new filename

### ISSUE THREAD

**Issue by yushan777** [TMElyralab/MusePose#21]
Yolox link points to file name `yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth`

it needs to be renamed to `yolox_l_8x8_300e_coco.pth` in order to work.

**Comment by ansonkao** [comment]
Added a note in https://github.com/TMElyralab/MusePose/compare/main...ansonkao:MusePose:patch-2

**Comment by czk32611** [comment]
Merged. Thanks!
