### ISSUE TITLE
Missing body parts

### ISSUE THREAD

**Issue by ANDYVDL** [TMElyralab/MusePose#23]
Love playing around with the model so far! Awesome work!

The legs are missing in the pose. Is there a way to use the body positioning of the video instead or get all limbs from the picture?

https://github.com/TMElyralab/MusePose/assets/21038658/34eb1f65-b03e-490b-9644-39a459eb77ab

**Comment by TZYSJTU** [comment]
That's because the provided video does not have the missing part at all, which the pose align algorithm can never predict. We suggest you to use full-body inputs for both the image and the video.
