### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by xy-soft** [TMElyralab/MusePose#24]
CUDA out of memory. Tried to allocate 1.05 GiB (GPU 0; 23.64 GiB total capacity; 14.04 GiB already allocated; 74.44 MiB free; 14.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

通常建议多少的显存可以正常运行？

**Comment by xy-soft** [comment]
可以并行使用多个显卡吗

**Comment by TZYSJTU** [comment]
please refer to https://github.com/TMElyralab/MusePose/issues/6#issuecomment-2136933975
