### ISSUE TITLE
How to keep fps the same as video source

### ISSUE THREAD

**Issue by SWAPv1** [TMElyralab/MusePose#26]
First of all this is a amazing opensource tool so thank you developers!

The default example video is 24fps.
But the final video is 12fps.

How can I adjust the  "python test_stage_2.py --config ./configs/test_stage_2.yaml" command to make it use the same fps.

Currently if I type in "python test_stage_2.py --config ./configs/test_stage_2.yaml --fps 24" it will output 24fps but it will be 2x the speed too which is not what I want.

**Comment by TZYSJTU** [comment]
Just set skip=0， but it will take twice the time to generate since the frame number is doubled.

**Comment by SWAPv1** [comment]
What is the exact name of that part and which file do I set skip=0?

**Comment by TZYSJTU** [comment]
> What is the exact name of that part and which file do I set skip=0?

test_stage_2.py
