### ISSUE TITLE
建个群吧，大家可以方便交流

### ISSUE THREAD

**Issue by chmod777john** [TMElyralab/MusePose#35]
建立一个微信群，方便大家交流 MusePose

![image](https://github.com/TMElyralab/MusePose/assets/146207719/be88a4d7-cd3b-41f6-a34c-e025b437c98f)

**Comment by jojokic** [comment]
过期了

**Comment by chmod777john** [comment]
> 过期了

已更新

**Comment by xfguo-ucas** [comment]
@chmod777john 过期了，求个wx，我加你把

**Comment by wangqiang9** [comment]
过期了，求更新

**Comment by husthdd** [comment]
二维码过期了，求更新

**Comment by benben-three** [comment]
现在更新了
![image](https://github.com/TMElyralab/MusePose/assets/174762840/62290c39-a71d-49b6-83b4-084ffeddc092)

**Comment by benben-three** [comment]
群主微信号是 dreamingforhope 如果还过期的话可以直接添加群主

**Comment by chmod777john** [comment]
> @chmod777john 过期了，求个wx，我加你把

微信 dreamingforhope 
如果过期而没有更新链接的话，可以加我微信然后拉入群聊
