### ISSUE TITLE
Is there a way to use full face keypoints too?

### ISSUE THREAD

**Issue by G-force78** [TMElyralab/MusePose#37]
Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? 
https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4

**Comment by TZYSJTU** [comment]
Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48
But the result will be wrong because we did not draw the face during training.

**Comment by TZYSJTU** [comment]
> Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4

Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48
But the result will be wrong because we did not draw the face during training.

**Comment by zhanghongyong123456** [comment]
> > Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4
> 
> Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48 But the result will be wrong because we did not draw the face during training.

[TZYSJTU](https://github.com/TZYSJTU)，
1. yes，I test  with  face，Get blurry faces

https://github.com/TMElyralab/MusePose/assets/48466610/948ba738-1931-4220-9ffe-343efe248a2f
2.  I want to know how to click the blue dot on  finger
![image](https://github.com/TMElyralab/MusePose/assets/48466610/247e3178-61f8-4b05-ad6e-c3f2c5ef5667)

**Comment by TZYSJTU** [comment]
> > > Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4
> > 
> > 
> > Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48 But the result will be wrong because we did not draw the face during training.
> 
> [TZYSJTU](https://github.com/TZYSJTU)，
> 
> 1. yes，I test  with  face，Get blurry faces
> 
> https://github.com/TMElyralab/MusePose/assets/48466610/948ba738-1931-4220-9ffe-343efe248a2f 2. I want to know how to remove the blue dot on finger ![image](https://private-user-images.githubusercontent.com/48466610/335949991-247e3178-61f8-4b05-ad6e-c3f2c5ef5667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTY2MjcsIm5iZiI6MTcxNzM5NjMyNywicGF0aCI6Ii80ODQ2NjYxMC8zMzU5NDk5OTEtMjQ3ZTMxNzgtNjFmOC00YjA1LWFkNmUtYzNmMmM1ZWY1NjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMmY2OTQyYjcxMjQ4YTM2NjY4YmFkYTIxNTc4ODkyOWQ0YTU4NmFjNWY0ZWQxZmY2MGFmMTliMjc0MThhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAuyJcprlY1vdji1Hm9hYWioRf1-Y7pLQv0ohtP_65s)

rgb <-> bgr. 
Just change the channel order of the img.

**Comment by zhanghongyong123456** [comment]
> > > > Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4
> > > 
> > > 
> > > Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48 But the result will be wrong because we did not draw the face during training.
> > 
> > 
> > [TZYSJTU](https://github.com/TZYSJTU)，
> > 
> > 1. yes，I test  with  face，Get blurry faces
> > 
> > https://github.com/TMElyralab/MusePose/assets/48466610/948ba738-1931-4220-9ffe-343efe248a2f 2. I want to know how to remove the blue dot on finger ![image](https://private-user-images.githubusercontent.com/48466610/335949991-247e3178-61f8-4b05-ad6e-c3f2c5ef5667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTY2MjcsIm5iZiI6MTcxNzM5NjMyNywicGF0aCI6Ii80ODQ2NjYxMC8zMzU5NDk5OTEtMjQ3ZTMxNzgtNjFmOC00YjA1LWFkNmUtYzNmMmM1ZWY1NjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMmY2OTQyYjcxMjQ4YTM2NjY4YmFkYTIxNTc4ODkyOWQ0YTU4NmFjNWY0ZWQxZmY2MGFmMTliMjc0MThhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAuyJcprlY1vdji1Hm9hYWioRf1-Y7pLQv0ohtP_65s)
> 
> rgb <-> bgr. Just change the channel order of the img.

OK , about  pose  align  video  (About whether RGB or BGR format affects video generation?),For hand generation, rgb effect is not as good as bgr effect, is that true, or is it caused by my different alignment pose

**Comment by TZYSJTU** [comment]
> > > > > Hi, great work the consistency across frames is superb, I noticed you developed it partly from moore animate anyone, is there a way to use the face keypoints thay they use? https://github.com/MooreThreads/Moore-AnimateAnyone/blob/master/configs/inference/pose_videos/anyone-video-4_kps.mp4
> > > > 
> > > > 
> > > > Yes, you can set `draw_face = True` in https://github.com/TMElyralab/MusePose/blob/main/pose/script/dwpose.py#L48 But the result will be wrong because we did not draw the face during training.
> > > 
> > > 
> > > [TZYSJTU](https://github.com/TZYSJTU)，
> > > 
> > > 1. yes，I test  with  face，Get blurry faces
> > > 
> > > https://github.com/TMElyralab/MusePose/assets/48466610/948ba738-1931-4220-9ffe-343efe248a2f 2. I want to know how to remove the blue dot on finger ![image](https://private-user-images.githubusercontent.com/48466610/335949991-247e3178-61f8-4b05-ad6e-c3f2c5ef5667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTY2MjcsIm5iZiI6MTcxNzM5NjMyNywicGF0aCI6Ii80ODQ2NjYxMC8zMzU5NDk5OTEtMjQ3ZTMxNzgtNjFmOC00YjA1LWFkNmUtYzNmMmM1ZWY1NjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMmY2OTQyYjcxMjQ4YTM2NjY4YmFkYTIxNTc4ODkyOWQ0YTU4NmFjNWY0ZWQxZmY2MGFmMTliMjc0MThhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAuyJcprlY1vdji1Hm9hYWioRf1-Y7pLQv0ohtP_65s)
> > 
> > 
> > rgb <-> bgr. Just change the channel order of the img.
> 
> OK , about pose align video (About whether RGB or BGR format affects video generation?),For hand generation, rgb effect is not as good as bgr effect, is that true, or is it caused by my different alignment pose

During training, we use the red finger. So keep it same when testing should be better.
