### ISSUE TITLE
About arxiv paper

### ISSUE THREAD

**Issue by resindraburiza** [TMElyralab/MusePose#41]
Dear MusePose authors,

First of all, thank you very much for sharing your incredible works. I really appreaciate it.

I am interested in the technical details of MusePose. In the github readme, it seems that there is a citation information but I cannot seem to find the referenced paper in anywhere. 

> @article{musepose,
  title={MusePose: a Pose-Driven Image-to-Video Framework for Virtual Human Generation},
  author={Tong, Zhengyan and Li, Chao and Chen, Zhaokang and Wu, Bin and Zhou, Wenjiang},
  journal={arxiv},
  year={2024}
}

Could you please share the direct link to the paper? Will you release the paper too? 
Thank you very much. Looking forward to hear from you.

**Comment by TZYSJTU** [comment]
We have no plans to write an academic paper at this time. But we may write a short technical report to teach users how to train the model and how to perform inference to get good results.

**Comment by TZYSJTU** [comment]
> Dear MusePose authors,
> 
> First of all, thank you very much for sharing your incredible works. I really appreaciate it.
> 
> I am interested in the technical details of MusePose. In the github readme, it seems that there is a citation information but I cannot seem to find the referenced paper in anywhere.
> 
> > @Article{musepose,
> > title={MusePose: a Pose-Driven Image-to-Video Framework for Virtual Human Generation},
> > author={Tong, Zhengyan and Li, Chao and Chen, Zhaokang and Wu, Bin and Zhou, Wenjiang},
> > journal={arxiv},
> > year={2024}
> > }
> 
> Could you please share the direct link to the paper? Will you release the paper too? Thank you very much. Looking forward to hear from you.

We have no plans to write an academic paper at this time. But we may write a short technical report to teach users how to train the model and how to perform inference to get good results.

**Comment by zhangxujinsh** [comment]
Looking forward to the report!

**Comment by resindraburiza** [comment]
@TZYSJTU ,

thank you for the answer. I understand that the citation part on the readme is just a placeholder for now. I too looking forward for the technical report! 

Best,
