### ISSUE TITLE
pose align got bad result when set "draw_face=True"

### ISSUE THREAD

**Issue by BugsMaker0513** [TMElyralab/MusePose#42]
[
![20240606-103036](https://github.com/TMElyralab/MusePose/assets/51353570/c1f3d6ca-6d5b-4924-9996-136c017cf249)
](url)

**Comment by TZYSJTU** [comment]
> [ ![20240606-103036](https://private-user-images.githubusercontent.com/51353570/337079866-c1f3d6ca-6d5b-4924-9996-136c017cf249.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjAxMjQsIm5iZiI6MTcxNzY1OTgyNCwicGF0aCI6Ii81MTM1MzU3MC8zMzcwNzk4NjYtYzFmM2Q2Y2EtNmQ1Yi00OTI0LTk5OTYtMTM2YzAxN2NmMjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNzQzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjY2ZWQ1NmNkYmJjZDA1Mjg1MTI0NjU1NzM5MTFmOTVlZTA5YTViMjcwYWM3MDRjZmRhN2IyNmY5NTlmZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ej4Wsc_hYrFMp0NXzzMR6AEFpeg9FbbxNAgc4VqV6xI) ](url)

Hi, we did not draw face during training, so the pose align code keeps the face keypoints unaligned

**Comment by BugsMaker0513** [comment]
> > [ ![20240606-103036](https://private-user-images.githubusercontent.com/51353570/337079866-c1f3d6ca-6d5b-4924-9996-136c017cf249.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjAxMjQsIm5iZiI6MTcxNzY1OTgyNCwicGF0aCI6Ii81MTM1MzU3MC8zMzcwNzk4NjYtYzFmM2Q2Y2EtNmQ1Yi00OTI0LTk5OTYtMTM2YzAxN2NmMjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNzQzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjY2ZWQ1NmNkYmJjZDA1Mjg1MTI0NjU1NzM5MTFmOTVlZTA5YTViMjcwYWM3MDRjZmRhN2IyNmY5NTlmZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ej4Wsc_hYrFMp0NXzzMR6AEFpeg9FbbxNAgc4VqV6xI) ](url)
> 
> Hi, we did not draw face during training, so the pose align code keeps the face keypoints unaligned

Would you align the face in future version?
And,  what is the reason of not using face during training?

**Comment by TZYSJTU** [comment]
> > > [ ![20240606-103036](https://private-user-images.githubusercontent.com/51353570/337079866-c1f3d6ca-6d5b-4924-9996-136c017cf249.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjAxMjQsIm5iZiI6MTcxNzY1OTgyNCwicGF0aCI6Ii81MTM1MzU3MC8zMzcwNzk4NjYtYzFmM2Q2Y2EtNmQ1Yi00OTI0LTk5OTYtMTM2YzAxN2NmMjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNzQzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjY2ZWQ1NmNkYmJjZDA1Mjg1MTI0NjU1NzM5MTFmOTVlZTA5YTViMjcwYWM3MDRjZmRhN2IyNmY5NTlmZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ej4Wsc_hYrFMp0NXzzMR6AEFpeg9FbbxNAgc4VqV6xI) ](url)
> > 
> > 
> > Hi, we did not draw face during training, so the pose align code keeps the face keypoints unaligned
> 
> Would you align the face in future version? And, what is the reason of not using face during training?

No, because we found drawing face caused over control of the face and much worse results.You can see that Alibaba's AnimateAnyone  also has no face.
