### ISSUE TITLE
CUDA out of memory on 8 GB VRAM + 8 GB shared RAM

### ISSUE THREAD

**Issue by nitinmukesh** [TMElyralab/MusePose#7]
I installed it on Windows 11 but getting the CUDA out of memory error. I reduced the dance video dimensions to half 540 x 960 still the same.

Anyway to make it work by tweaking any settings like batch size etc....

**Comment by BlacknoSheep** [comment]
Try
```
python test_stage_2.py --config ./configs/test_stage_2.yaml -W 200 -H 350
```

**Comment by TZYSJTU** [comment]
Please refer to https://github.com/TMElyralab/MusePose/issues/6#issuecomment-2136933975

**Comment by nitinmukesh** [comment]
> Try
> 
> ```
> python test_stage_2.py --config ./configs/test_stage_2.yaml -W 200 -H 350
> ```

Thank you. Following worked for me
python test_stage_2.py --config ./configs/test_stage_2.yaml -W 360 -H 640
