### ISSUE TITLE
Error on stage 2

### ISSUE THREAD

**Issue by speedyrulz** [TMElyralab/MusePose#8]
I'm getting this error on stage 2, any idea what could be going on?

PS G:\musepose> python test_stage_2.py --config ./configs/test_stage_2.yaml
Traceback (most recent call last):
  File "G:\musepose\test_stage_2.py", line 21, in <module>
    from musepose.models.pose_guider import PoseGuider
ModuleNotFoundError: No module named 'musepose'

**Comment by nitinmukesh** [comment]
Not sure what could be the issue as it installed fine in the first attempt. Please refer this
https://www.youtube.com/watch?v=x_zlatUuWoo

**Comment by Dawgmastah** [comment]
Same exact error,  in my case chatgpt suggesteed adding msuepose folders to PATH but didnt solve

**Comment by Dawgmastah** [comment]
The error was that my folder was MusePose in camelcase and not lowercase as in the github.
As well as the instructions are missing the torc with cusa instructions found in the video.

**Comment by speedyrulz** [comment]
> The error was that my folder was MusePose in camelcase and not lowercase as in the github. As well as the instructions are missing the torc with cusa instructions found in the video.

Awesome. That fixed it for me too.
